apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-cert
  namespace: cert-manager
spec:
  commonName: "Kubernetes Admin"
  duration: 131400h # 15 years
  secretName: admin-cert-key-pair
  usages:
    - client auth
  issuerRef:
    name: intermediate-ca
    kind: ClusterIssuer
    group: cert-manager.io