apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-cert
  namespace: default
spec:
  secretName: admin-cert-secret
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
  commonName: admin@example.com
  duration: 540h # 15 years
  renewBefore: 360h # 15 days
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth