apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ext-dev-cert
  namespace: default
spec:
  secretName: ext-dev-cert-secret
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
  commonName: external-developer@example.com
  duration: 720h # 2 years
  renewBefore: 360h # 15 days
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth