apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qa-dev-cert
  namespace: your-namespace
spec:
  secretName: qa-dev-cert-secret
  issuerRef:
    name: intermediate-ca
    kind: Issuer
  commonName: qa-dev@example.com
  duration: 15y
  renewBefore: 30d
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth