apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ext-dev-binding
  namespace: default
subjects:
- kind: User
  name: external-developer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ext-dev-role
  apiGroup: rbac.authorization.k8s.io