apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qa-developer-readonly
  namespace: qa
subjects:
- kind: User
  name: qa-developer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: view
  apiGroup: rbac.authorization.k8s.io
