apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: intermediate-ca
spec:
  ca:
    secretName: root-ca-key-pair
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: intermediate-ca-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: "Intermediate CA"
  duration: 438000h # 50 years
  secretName: intermediate-ca-key-pair
  issuerRef:
    name: intermediate-ca
    kind: ClusterIssuer
    group: cert-manager.io