apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: intermediate-ca
  namespace: cert-manager
spec:
  secretName: intermediate-ca-secret
  issuerRef:
    name: root-ca
    kind: ClusterIssuer
  duration: 876000h # 100 years
  renewBefore: 720h # 30 days
  commonName: intermediate-ca
  isCA: true
  usages:
    - cert sign
    - crl sign
    - server auth
    - client auth