apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-ca
spec:
  ca:
    secretName: root-ca-secret
    duration: 50y
    renewBefore: 30d
    privateKey: |
      -----BEGIN PRIVATE KEY-----
      <your-private-key-here>
      -----END PRIVATE KEY-----
    certificate: |
      -----BEGIN CERTIFICATE-----
      <your-certificate-here>
      -----END CERTIFICATE-----